### PR TITLE
tableview frame calculation

### PR DESCRIPTION
**Pull request by barnardn**
getting the keyboard into the same coord space as the window of the table view seems to be sufficient - it not more accurate.

This method seems to be more accurate. Prior to this change, if the form table view controller was presented in page sheet mode and in landscape orientation, the computed content offset would push the first uitextfield out of visibility.

A second pair of eyes would be nice to see if this fix addresses the problem or the issue lies somewhere else.

Also, not sure why the CI build fails. The code compiles and checks out..

### CODE REVIEW

**Comment by willbur1984** [comment]
The Travis-CI builds fail because the project links against 10.10 only frameworks. They still do all their builds on 10.9 machines :(

I'll look at this tonight and merge it in.

**Comment by willbur1984** [comment]
whoops, i read page sheet instead of form sheet presentation. it looks like it doesn't handle page sheet correctly either. i will test using form sheet, might open a new issue for page sheet.

**Comment by barnardn** [comment]
the numbers for the intersect rect values were weird no matter how i looked at them. also, i hardcoded several test values for the inset height and it seemed like you had to specify a pretty large number, say 225, to even get the tableview to scroll at all. not quite sure what to make of that.

**Comment by willbur1984** [comment]
i was trying to base the implementation off of https://github.com/nicklockwood/FXForms/blob/master/FXForms/FXForms.m#L2370

but it seems like even that doesn't handle presentations that aren't full screen. i haven't had much luck finding a reference implementation elsewhere. it seems like everyone assumes you only present full screen if you are using a form :(

**Comment by willbur1984** [comment]
going to mess with this more over the weekend, it seems like there has to be a straightforward solution

**Comment by willbur1984** [comment]
this is really strange. if i leave it up to `UITableViewController`, the insets are adjusted correctly, but ignored if the form view controller is a child view controller (like it is in the demo).

the solution might just be to advise subclassing instead of containment to ensure the system handles the keyboard positioning correctly. i cannot figure out why the code thats in won't function correctly in the cases discussed previously, but the system handles them without issue.

**Comment by willbur1984** [comment]
@barnardn not sure what the best solution is here, see my previous comment

**Comment by willbur1984** [comment]
@barnardn i noodled over this some more. i think the imperfect solution is to register for the keyboard notifications and within the callbacks check if we are embedded within another parent view controller. if so, attempt to move things to avoid the keyboard, otherwise do nothing as the system will handle it for us.

**Pull request merged**
